// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cctflcnhlfjtmlmywbcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjdGZsY25obGZqdG1sbXl3YmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDE3NDIsImV4cCI6MjA3MTgxNzc0Mn0.ZFP6YVPutkeHWUx60hTpDYBGAj0_CBz0KwPk5AnK2uI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});